2021-12-31 01:56:37,826 CRITICAL   server_logs_config.py Критическая ошибка
2021-12-31 01:56:37,826 ERROR      server_logs_config.py Ошибка
2021-12-31 01:56:37,826 DEBUG      server_logs_config.py Отладочная информация
2021-12-31 01:56:37,826 INFO       server_logs_config.py Информационное сообщение
2021-12-31 01:56:37,826 WARNING    server_logs_config.py Внимание
2022-01-11 17:47:07,732 INFO       server.py  Сервер запущен. Порт : 7777, адрес: 
2022-01-11 17:49:31,866 INFO       server.py  Соединение установлено с - ('127.0.0.1', 59897)
2022-01-11 17:49:31,866 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905371.8667462, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 17:49:40,865 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 59902)
2022-01-11 17:49:40,866 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905380.8659658, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 17:49:42,155 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 59903)
2022-01-11 17:49:42,156 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905382.1564221, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 17:49:43,555 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 59904)
2022-01-11 17:49:43,555 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905383.5555983, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 17:51:51,545 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 59911)
2022-01-11 17:51:51,546 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905511.5456934, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 17:51:52,692 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 59912)
2022-01-11 17:51:52,693 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905512.6924882, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 17:54:10,893 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 59929)
2022-01-11 17:54:10,893 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905650.8937657, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 17:54:19,302 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 59930)
2022-01-11 17:54:19,303 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905659.3022447, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 17:54:20,757 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 59931)
2022-01-11 17:54:20,757 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641905660.7576673, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 18:13:05,515 INFO       server.py  Сервер запущен. Порт : 7777, адрес: 
2022-01-11 19:36:14,653 INFO       server.py  Соединение установлено с - ('127.0.0.1', 60549)
2022-01-11 19:36:14,654 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641911774.6534817, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 19:36:17,915 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 60550)
2022-01-11 19:36:17,915 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641911777.9151564, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 19:37:49,930 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 60560)
2022-01-11 19:37:49,931 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641911869.9304485, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 19:38:50,013 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 60566)
2022-01-11 19:38:50,016 ERROR      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Не удалось декодировать сообщение от клиента ('127.0.0.1', 60566).
2022-01-11 19:40:08,738 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 60574)
2022-01-11 19:40:08,738 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641912008.7389653, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
2022-01-11 19:41:55,983 INFO       D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py Соединение установлено с - ('127.0.0.1', 60579)
2022-01-11 19:41:55,984 DEBUG      D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py  process_client_msg вызвана из функции server_main в модуле D:\PyCharm\Lerning_Client-server_app_Python\Lesson_4\server.py с аргументами: ({'action': 'presence', 'time': 1641912115.9833653, 'port': 7777, 'user': {'account_name': 'Evgeny'}},); {}
